# Generated by Django 2.2.4 on 2019-08-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes_app', '0002_auto_20190802_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['joke'],
            },
        ),
    ]
