# Generated by Django 2.2.4 on 2019-08-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes_app', '0003_userjoke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJoke',
        ),
    ]
